### ISSUE TITLE
Support using custom Drawable as placeholder

### ISSUE THREAD

**Issue by cloudymusic** [mklimek/FrameVideoView#3]
I think it would be nice if there was an additional overload of `setup()` that accepted a Drawable to use as a placeholder background, as an alternative (or in addition) to the background color that's already supported.

In my particular situation, I always know what the first frame of my videos will look like ahead of time, so it could be used to provide a more seamless transition once the video starts playing.

**Comment by mklimek** [comment]
Added in https://github.com/mklimek/FrameVideoView/commit/29c75966afa8aa6ca25a24360e74f924a8840faf

Enjoy :)

**Comment by cloudymusic** [comment]
Works perfectly. Thank you! :)
