### ISSUE TITLE
Can't turn off looping?

### ISSUE THREAD

**Issue by dylanreid** [mklimek/FrameVideoView#5]
Thanks for making this library available - I've been trying to use it but am running into an issue because of the ordering in TextureViewImpl.java's onPrepared() function.

In it, you execute the callback listener.mediaPlayerPrepared(), which is where I set mediaPlayer.setLooping(false). However, after returning from the call back, you explicitly call setLooping(true). There doesn't seem to be another chance for me to call setLooping before the video starts playing.

Any thoughts on how to get around this, am I missing something, or is this a bug?

Thanks!

**Comment by mklimek** [comment]
@dylanreid you're right it's a bug.
I've fixed it and released new 1.1.1 version :)

ec6a31ebbecf8d30a22cc8af91493ab85c9b90d7

**Comment by dylanreid** [comment]
Thanks for the super fast turnaround time on the fix!
