### ISSUE TITLE
Can we play Video from server URL

### ISSUE THREAD

**Issue by MhtSuthar** [mklimek/FrameVideoView#6]
Hi, 

I want to play video from server url, i am trying to replace local path to server url but cant play video and throwing exception, if you know then help me.

Thanx

**Comment by mklimek** [comment]
FrameVideoView is just a wrapper.
VideoView nad TextureView can handle it so with FrameVideoView you can do it too.

http://stackoverflow.com/questions/10736517/playing-video-on-textureview
http://stackoverflow.com/questions/2620049/how-to-play-video-from-url
